# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
git:
  depth: 99999
julia:
  - 0.6
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone("https://github.com/OpenMendel/SnpArrays.jl.git"); Pkg.build("SnpArrays");'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("ImputeZScore"); Pkg.test("ImputeZScore"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("ImputeZScore")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("ImputeZScore")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("ImputeZScore")); include(joinpath("docs", "make.jl"))'
