# Project information
site_name: 'ImputeZScore.jl'
site_description: 'Imputation of GWAS summary association data'
site_author: 'Huwenbo Shi'
site_url: 'https://huwenboshi.github.io/ImputeZScore.jl'

# Repository
repo_url: 'https://github.com/huwenboshi/ImputeZScore.jl'

# Copyright
copyright: 'Copyright &copy; 2017 - 2022 Huwenbo Shi'

# Documentation and theme
theme: 'material'

# define pages
pages:
    - Home: 'index.md'
    - Input Format: 'input_format.md'
    - Impute Z Score: 'impute_zscore.md'

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  social:
    - type: 'github'
      link: 'https://github.com/huwenboshi'
    - type: 'twitter'
      link: 'https://twitter.com/shihuwenbo'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/john-doe'

# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - mdx_math
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
